[project]
name = "ijv-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "mkdoc>=0.1",
    "mkdocs-jupyter>=0.24.8",
    "mkdocs>=1.6.1",
    "python-markdown-math>=0.8",
]
